/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminExportRouteImport } from './routes/api/admin/export'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExportRoute = ApiAdminExportRouteImport.update({
  id: '/api/admin/export',
  path: '/api/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/export': typeof ApiAdminExportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/export': typeof ApiAdminExportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/export': typeof ApiAdminExportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/export'
    | '/admin/login'
    | '/api/bookings'
    | '/admin/'
    | '/api/admin/bookings'
    | '/api/admin/export'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/export'
    | '/admin/login'
    | '/api/bookings'
    | '/admin'
    | '/api/admin/bookings'
    | '/api/admin/export'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
  id:
    | '__root__'
    | '/'
    | '/admin/export'
    | '/admin/login'
    | '/api/bookings'
    | '/admin/'
    | '/api/admin/bookings'
    | '/api/admin/export'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRoute
  ApiAdminExportRoute: typeof ApiAdminExportRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/export': {
      id: '/api/admin/export'
      path: '/api/admin/export'
      fullPath: '/api/admin/export'
      preLoaderRoute: typeof ApiAdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminExportRoute: AdminExportRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRoute,
  ApiAdminExportRoute: ApiAdminExportRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
