/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesWarehousingStoragePuneRouteImport } from './routes/services/warehousing-storage-pune'
import { Route as ServicesOfficeRelocationPuneRouteImport } from './routes/services/office-relocation-pune'
import { Route as ServicesHomeShiftingPuneRouteImport } from './routes/services/home-shifting-pune'
import { Route as ServicesCarBikeTransportPuneRouteImport } from './routes/services/car-bike-transport-pune'
import { Route as BlogPackingTipsForMovingRouteImport } from './routes/blog/packing-tips-for-moving'
import { Route as BlogPackersMoversChargesPuneRouteImport } from './routes/blog/packers-movers-charges-pune'
import { Route as BlogMovingDuringMonsoonPuneRouteImport } from './routes/blog/moving-during-monsoon-pune'
import { Route as BlogHowToChoosePackersMoversRouteImport } from './routes/blog/how-to-choose-packers-movers'
import { Route as BlogDocumentsForVehicleTransportRouteImport } from './routes/blog/documents-for-vehicle-transport'
import { Route as AreasWakadRouteImport } from './routes/areas/wakad'
import { Route as AreasPimpriChinchwadRouteImport } from './routes/areas/pimpri-chinchwad'
import { Route as AreasNigdiRouteImport } from './routes/areas/nigdi'
import { Route as AreasHinjewadiRouteImport } from './routes/areas/hinjewadi'
import { Route as AreasBhosariRouteImport } from './routes/areas/bhosari'
import { Route as AreasBanerRouteImport } from './routes/areas/baner'
import { Route as AreasAundhRouteImport } from './routes/areas/aundh'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminExportRouteImport } from './routes/api/admin/export'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWarehousingStoragePuneRoute =
  ServicesWarehousingStoragePuneRouteImport.update({
    id: '/services/warehousing-storage-pune',
    path: '/services/warehousing-storage-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesOfficeRelocationPuneRoute =
  ServicesOfficeRelocationPuneRouteImport.update({
    id: '/services/office-relocation-pune',
    path: '/services/office-relocation-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHomeShiftingPuneRoute =
  ServicesHomeShiftingPuneRouteImport.update({
    id: '/services/home-shifting-pune',
    path: '/services/home-shifting-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCarBikeTransportPuneRoute =
  ServicesCarBikeTransportPuneRouteImport.update({
    id: '/services/car-bike-transport-pune',
    path: '/services/car-bike-transport-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPackingTipsForMovingRoute =
  BlogPackingTipsForMovingRouteImport.update({
    id: '/blog/packing-tips-for-moving',
    path: '/blog/packing-tips-for-moving',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPackersMoversChargesPuneRoute =
  BlogPackersMoversChargesPuneRouteImport.update({
    id: '/blog/packers-movers-charges-pune',
    path: '/blog/packers-movers-charges-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMovingDuringMonsoonPuneRoute =
  BlogMovingDuringMonsoonPuneRouteImport.update({
    id: '/blog/moving-during-monsoon-pune',
    path: '/blog/moving-during-monsoon-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToChoosePackersMoversRoute =
  BlogHowToChoosePackersMoversRouteImport.update({
    id: '/blog/how-to-choose-packers-movers',
    path: '/blog/how-to-choose-packers-movers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDocumentsForVehicleTransportRoute =
  BlogDocumentsForVehicleTransportRouteImport.update({
    id: '/blog/documents-for-vehicle-transport',
    path: '/blog/documents-for-vehicle-transport',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasWakadRoute = AreasWakadRouteImport.update({
  id: '/areas/wakad',
  path: '/areas/wakad',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasPimpriChinchwadRoute = AreasPimpriChinchwadRouteImport.update({
  id: '/areas/pimpri-chinchwad',
  path: '/areas/pimpri-chinchwad',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasNigdiRoute = AreasNigdiRouteImport.update({
  id: '/areas/nigdi',
  path: '/areas/nigdi',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasHinjewadiRoute = AreasHinjewadiRouteImport.update({
  id: '/areas/hinjewadi',
  path: '/areas/hinjewadi',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasBhosariRoute = AreasBhosariRouteImport.update({
  id: '/areas/bhosari',
  path: '/areas/bhosari',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasBanerRoute = AreasBanerRouteImport.update({
  id: '/areas/baner',
  path: '/areas/baner',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAundhRoute = AreasAundhRouteImport.update({
  id: '/areas/aundh',
  path: '/areas/aundh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExportRoute = ApiAdminExportRouteImport.update({
  id: '/api/admin/export',
  path: '/api/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/areas/aundh': typeof AreasAundhRoute
  '/areas/baner': typeof AreasBanerRoute
  '/areas/bhosari': typeof AreasBhosariRoute
  '/areas/hinjewadi': typeof AreasHinjewadiRoute
  '/areas/nigdi': typeof AreasNigdiRoute
  '/areas/pimpri-chinchwad': typeof AreasPimpriChinchwadRoute
  '/areas/wakad': typeof AreasWakadRoute
  '/blog/documents-for-vehicle-transport': typeof BlogDocumentsForVehicleTransportRoute
  '/blog/how-to-choose-packers-movers': typeof BlogHowToChoosePackersMoversRoute
  '/blog/moving-during-monsoon-pune': typeof BlogMovingDuringMonsoonPuneRoute
  '/blog/packers-movers-charges-pune': typeof BlogPackersMoversChargesPuneRoute
  '/blog/packing-tips-for-moving': typeof BlogPackingTipsForMovingRoute
  '/services/car-bike-transport-pune': typeof ServicesCarBikeTransportPuneRoute
  '/services/home-shifting-pune': typeof ServicesHomeShiftingPuneRoute
  '/services/office-relocation-pune': typeof ServicesOfficeRelocationPuneRoute
  '/services/warehousing-storage-pune': typeof ServicesWarehousingStoragePuneRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/export': typeof ApiAdminExportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/areas/aundh': typeof AreasAundhRoute
  '/areas/baner': typeof AreasBanerRoute
  '/areas/bhosari': typeof AreasBhosariRoute
  '/areas/hinjewadi': typeof AreasHinjewadiRoute
  '/areas/nigdi': typeof AreasNigdiRoute
  '/areas/pimpri-chinchwad': typeof AreasPimpriChinchwadRoute
  '/areas/wakad': typeof AreasWakadRoute
  '/blog/documents-for-vehicle-transport': typeof BlogDocumentsForVehicleTransportRoute
  '/blog/how-to-choose-packers-movers': typeof BlogHowToChoosePackersMoversRoute
  '/blog/moving-during-monsoon-pune': typeof BlogMovingDuringMonsoonPuneRoute
  '/blog/packers-movers-charges-pune': typeof BlogPackersMoversChargesPuneRoute
  '/blog/packing-tips-for-moving': typeof BlogPackingTipsForMovingRoute
  '/services/car-bike-transport-pune': typeof ServicesCarBikeTransportPuneRoute
  '/services/home-shifting-pune': typeof ServicesHomeShiftingPuneRoute
  '/services/office-relocation-pune': typeof ServicesOfficeRelocationPuneRoute
  '/services/warehousing-storage-pune': typeof ServicesWarehousingStoragePuneRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/export': typeof ApiAdminExportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/areas/aundh': typeof AreasAundhRoute
  '/areas/baner': typeof AreasBanerRoute
  '/areas/bhosari': typeof AreasBhosariRoute
  '/areas/hinjewadi': typeof AreasHinjewadiRoute
  '/areas/nigdi': typeof AreasNigdiRoute
  '/areas/pimpri-chinchwad': typeof AreasPimpriChinchwadRoute
  '/areas/wakad': typeof AreasWakadRoute
  '/blog/documents-for-vehicle-transport': typeof BlogDocumentsForVehicleTransportRoute
  '/blog/how-to-choose-packers-movers': typeof BlogHowToChoosePackersMoversRoute
  '/blog/moving-during-monsoon-pune': typeof BlogMovingDuringMonsoonPuneRoute
  '/blog/packers-movers-charges-pune': typeof BlogPackersMoversChargesPuneRoute
  '/blog/packing-tips-for-moving': typeof BlogPackingTipsForMovingRoute
  '/services/car-bike-transport-pune': typeof ServicesCarBikeTransportPuneRoute
  '/services/home-shifting-pune': typeof ServicesHomeShiftingPuneRoute
  '/services/office-relocation-pune': typeof ServicesOfficeRelocationPuneRoute
  '/services/warehousing-storage-pune': typeof ServicesWarehousingStoragePuneRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/export': typeof ApiAdminExportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/admin/export'
    | '/admin/login'
    | '/api/bookings'
    | '/api/contact'
    | '/areas/aundh'
    | '/areas/baner'
    | '/areas/bhosari'
    | '/areas/hinjewadi'
    | '/areas/nigdi'
    | '/areas/pimpri-chinchwad'
    | '/areas/wakad'
    | '/blog/documents-for-vehicle-transport'
    | '/blog/how-to-choose-packers-movers'
    | '/blog/moving-during-monsoon-pune'
    | '/blog/packers-movers-charges-pune'
    | '/blog/packing-tips-for-moving'
    | '/services/car-bike-transport-pune'
    | '/services/home-shifting-pune'
    | '/services/office-relocation-pune'
    | '/services/warehousing-storage-pune'
    | '/admin/'
    | '/api/admin/bookings'
    | '/api/admin/export'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/admin/export'
    | '/admin/login'
    | '/api/bookings'
    | '/api/contact'
    | '/areas/aundh'
    | '/areas/baner'
    | '/areas/bhosari'
    | '/areas/hinjewadi'
    | '/areas/nigdi'
    | '/areas/pimpri-chinchwad'
    | '/areas/wakad'
    | '/blog/documents-for-vehicle-transport'
    | '/blog/how-to-choose-packers-movers'
    | '/blog/moving-during-monsoon-pune'
    | '/blog/packers-movers-charges-pune'
    | '/blog/packing-tips-for-moving'
    | '/services/car-bike-transport-pune'
    | '/services/home-shifting-pune'
    | '/services/office-relocation-pune'
    | '/services/warehousing-storage-pune'
    | '/admin'
    | '/api/admin/bookings'
    | '/api/admin/export'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/admin/export'
    | '/admin/login'
    | '/api/bookings'
    | '/api/contact'
    | '/areas/aundh'
    | '/areas/baner'
    | '/areas/bhosari'
    | '/areas/hinjewadi'
    | '/areas/nigdi'
    | '/areas/pimpri-chinchwad'
    | '/areas/wakad'
    | '/blog/documents-for-vehicle-transport'
    | '/blog/how-to-choose-packers-movers'
    | '/blog/moving-during-monsoon-pune'
    | '/blog/packers-movers-charges-pune'
    | '/blog/packing-tips-for-moving'
    | '/services/car-bike-transport-pune'
    | '/services/home-shifting-pune'
    | '/services/office-relocation-pune'
    | '/services/warehousing-storage-pune'
    | '/admin/'
    | '/api/admin/bookings'
    | '/api/admin/export'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiContactRoute: typeof ApiContactRoute
  AreasAundhRoute: typeof AreasAundhRoute
  AreasBanerRoute: typeof AreasBanerRoute
  AreasBhosariRoute: typeof AreasBhosariRoute
  AreasHinjewadiRoute: typeof AreasHinjewadiRoute
  AreasNigdiRoute: typeof AreasNigdiRoute
  AreasPimpriChinchwadRoute: typeof AreasPimpriChinchwadRoute
  AreasWakadRoute: typeof AreasWakadRoute
  BlogDocumentsForVehicleTransportRoute: typeof BlogDocumentsForVehicleTransportRoute
  BlogHowToChoosePackersMoversRoute: typeof BlogHowToChoosePackersMoversRoute
  BlogMovingDuringMonsoonPuneRoute: typeof BlogMovingDuringMonsoonPuneRoute
  BlogPackersMoversChargesPuneRoute: typeof BlogPackersMoversChargesPuneRoute
  BlogPackingTipsForMovingRoute: typeof BlogPackingTipsForMovingRoute
  ServicesCarBikeTransportPuneRoute: typeof ServicesCarBikeTransportPuneRoute
  ServicesHomeShiftingPuneRoute: typeof ServicesHomeShiftingPuneRoute
  ServicesOfficeRelocationPuneRoute: typeof ServicesOfficeRelocationPuneRoute
  ServicesWarehousingStoragePuneRoute: typeof ServicesWarehousingStoragePuneRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRoute
  ApiAdminExportRoute: typeof ApiAdminExportRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/warehousing-storage-pune': {
      id: '/services/warehousing-storage-pune'
      path: '/services/warehousing-storage-pune'
      fullPath: '/services/warehousing-storage-pune'
      preLoaderRoute: typeof ServicesWarehousingStoragePuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/office-relocation-pune': {
      id: '/services/office-relocation-pune'
      path: '/services/office-relocation-pune'
      fullPath: '/services/office-relocation-pune'
      preLoaderRoute: typeof ServicesOfficeRelocationPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/home-shifting-pune': {
      id: '/services/home-shifting-pune'
      path: '/services/home-shifting-pune'
      fullPath: '/services/home-shifting-pune'
      preLoaderRoute: typeof ServicesHomeShiftingPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/car-bike-transport-pune': {
      id: '/services/car-bike-transport-pune'
      path: '/services/car-bike-transport-pune'
      fullPath: '/services/car-bike-transport-pune'
      preLoaderRoute: typeof ServicesCarBikeTransportPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/packing-tips-for-moving': {
      id: '/blog/packing-tips-for-moving'
      path: '/blog/packing-tips-for-moving'
      fullPath: '/blog/packing-tips-for-moving'
      preLoaderRoute: typeof BlogPackingTipsForMovingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/packers-movers-charges-pune': {
      id: '/blog/packers-movers-charges-pune'
      path: '/blog/packers-movers-charges-pune'
      fullPath: '/blog/packers-movers-charges-pune'
      preLoaderRoute: typeof BlogPackersMoversChargesPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/moving-during-monsoon-pune': {
      id: '/blog/moving-during-monsoon-pune'
      path: '/blog/moving-during-monsoon-pune'
      fullPath: '/blog/moving-during-monsoon-pune'
      preLoaderRoute: typeof BlogMovingDuringMonsoonPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-choose-packers-movers': {
      id: '/blog/how-to-choose-packers-movers'
      path: '/blog/how-to-choose-packers-movers'
      fullPath: '/blog/how-to-choose-packers-movers'
      preLoaderRoute: typeof BlogHowToChoosePackersMoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/documents-for-vehicle-transport': {
      id: '/blog/documents-for-vehicle-transport'
      path: '/blog/documents-for-vehicle-transport'
      fullPath: '/blog/documents-for-vehicle-transport'
      preLoaderRoute: typeof BlogDocumentsForVehicleTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/wakad': {
      id: '/areas/wakad'
      path: '/areas/wakad'
      fullPath: '/areas/wakad'
      preLoaderRoute: typeof AreasWakadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/pimpri-chinchwad': {
      id: '/areas/pimpri-chinchwad'
      path: '/areas/pimpri-chinchwad'
      fullPath: '/areas/pimpri-chinchwad'
      preLoaderRoute: typeof AreasPimpriChinchwadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/nigdi': {
      id: '/areas/nigdi'
      path: '/areas/nigdi'
      fullPath: '/areas/nigdi'
      preLoaderRoute: typeof AreasNigdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/hinjewadi': {
      id: '/areas/hinjewadi'
      path: '/areas/hinjewadi'
      fullPath: '/areas/hinjewadi'
      preLoaderRoute: typeof AreasHinjewadiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/bhosari': {
      id: '/areas/bhosari'
      path: '/areas/bhosari'
      fullPath: '/areas/bhosari'
      preLoaderRoute: typeof AreasBhosariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/baner': {
      id: '/areas/baner'
      path: '/areas/baner'
      fullPath: '/areas/baner'
      preLoaderRoute: typeof AreasBanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/aundh': {
      id: '/areas/aundh'
      path: '/areas/aundh'
      fullPath: '/areas/aundh'
      preLoaderRoute: typeof AreasAundhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/export': {
      id: '/api/admin/export'
      path: '/api/admin/export'
      fullPath: '/api/admin/export'
      preLoaderRoute: typeof ApiAdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  AdminExportRoute: AdminExportRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiContactRoute: ApiContactRoute,
  AreasAundhRoute: AreasAundhRoute,
  AreasBanerRoute: AreasBanerRoute,
  AreasBhosariRoute: AreasBhosariRoute,
  AreasHinjewadiRoute: AreasHinjewadiRoute,
  AreasNigdiRoute: AreasNigdiRoute,
  AreasPimpriChinchwadRoute: AreasPimpriChinchwadRoute,
  AreasWakadRoute: AreasWakadRoute,
  BlogDocumentsForVehicleTransportRoute: BlogDocumentsForVehicleTransportRoute,
  BlogHowToChoosePackersMoversRoute: BlogHowToChoosePackersMoversRoute,
  BlogMovingDuringMonsoonPuneRoute: BlogMovingDuringMonsoonPuneRoute,
  BlogPackersMoversChargesPuneRoute: BlogPackersMoversChargesPuneRoute,
  BlogPackingTipsForMovingRoute: BlogPackingTipsForMovingRoute,
  ServicesCarBikeTransportPuneRoute: ServicesCarBikeTransportPuneRoute,
  ServicesHomeShiftingPuneRoute: ServicesHomeShiftingPuneRoute,
  ServicesOfficeRelocationPuneRoute: ServicesOfficeRelocationPuneRoute,
  ServicesWarehousingStoragePuneRoute: ServicesWarehousingStoragePuneRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRoute,
  ApiAdminExportRoute: ApiAdminExportRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
